### ISSUE TITLE
Issues with PIP

### ISSUE THREAD

**Issue by dz0ny** [heroku/heroku-buildpack-python#192]
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-python.git
=====> Detected Framework: Python
Traceback (most recent call last):
  File "/tmp/buildpackLuGUb/vendor/pip-pop/pip-diff", line 114, in <module>
    main()
  File "/tmp/buildpackLuGUb/vendor/pip-pop/pip-diff", line 109, in main
    diff(**kwargs)
  File "/tmp/buildpackLuGUb/vendor/pip-pop/pip-diff", line 81, in diff
    r1 = Requirements(r1)
  File "/tmp/buildpackLuGUb/vendor/pip-pop/pip-diff", line 25, in __init__
    self.load(reqfile)
  File "/tmp/buildpackLuGUb/vendor/pip-pop/pip-diff", line 35, in load
    finder = PackageFinder([], [])
  File "/app/.heroku/python/lib/python2.7/site-packages/pip-6.0.6-py2.7.egg/pip/index.py", line 65, in __init__
    "PackageFinder() missing 1 required keyword argument: "
TypeError: PackageFinder() missing 1 required keyword argument: 'session'

**Comment by wenzou** [comment]
Same here

**Comment by dz0ny** [comment]
FYI Pinning buildpack to stable tag solves the problem. So it's definitely something with pip, setuptools upgrade.

```https://github.com/heroku/heroku-buildpack-python.git#v54```

**Comment by kennethreitz** [comment]
This bug should have been resolved earlier today. Is this occurring right now?

**Comment by dz0ny** [comment]
Yep, fresh builds are failing

**Comment by kennethreitz** [comment]
@dz0ny can you try again? A new version has been pushed that has new pip/setuptools. I suspect this is a bug in their codebases.
