### ISSUE TITLE
Numpy depended libraries (scipy) cause error

### ISSUE THREAD

**Issue by icoxfog417** [heroku/heroku-buildpack-python#210]
I faced the error when installing the `scipy`.
This error doesn't cause in local, and it haven't caused until merging the commits after 0382c31225344eabc7c0f66bf81eb4da332fea5f.

(I created the [buildpack for statistic libraries](https://github.com/icoxfog417/heroku-buildpack-python) and it worked fine until merging).

```
remote: -----> Installing dependencies with pip
remote:        Collecting scipy==0.15.1 (from -r requirements.txt (line 11))
remote:          Downloading scipy-0.15.1.tar.gz (11.4MB)
remote:        Installing collected packages: scipy
remote:          Running setup.py install for scipy
remote:            Complete output from command /app/.heroku/python/bin/python -c "import
setuptools, tokenize;__file__='/tmp/pip-build-q1wcmtuw/scipy/setup.py';exec(compile(getatt
r(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" inst
all --record /tmp/pip-wc6_bxsq-record/install-record.txt --single-version-externally-manag
ed --compile:
remote:            Traceback (most recent call last):
remote:              File "<string>", line 1, in <module>
remote:              File "/tmp/pip-build-q1wcmtuw/scipy/setup.py", line 249, in <module>
remote:                setup_package()
remote:              File "/tmp/pip-build-q1wcmtuw/scipy/setup.py", line 237, in setup_pac
kage
remote:                from numpy.distutils.core import setup
remote:              File "/app/.heroku/python/lib/python3.4/site-packages/numpy/__init__.
py", line 170, in <module>
remote:                from . import add_newdocs
remote:              File "/app/.heroku/python/lib/python3.4/site-packages/numpy/add_newdo
cs.py", line 13, in <module>
remote:                from numpy.lib import add_newdoc
remote:              File "/app/.heroku/python/lib/python3.4/site-packages/numpy/lib/__ini
t__.py", line 17, in <module>
remote:                from . import scimath as emath
remote:            ImportError: cannot import name 'scimath'
remote:
remote:            ----------------------------------------
remote:            Command "/app/.heroku/python/bin/python -c "import setuptools, tokenize
;__file__='/tmp/pip-build-q1wcmtuw/scipy/setup.py';exec(compile(getattr(tokenize, 'open',
open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pi
p-wc6_bxsq-record/install-record.txt --single-version-externally-managed --compile" failed
 with error code 1 in /tmp/pip-build-q1wcmtuw/scipy
```

Above error means that the python code can not resolve relative import (`ImportError: cannot import name 'scimath'`).

I think that it seems like #107.

**Comment by kennethreitz** [comment]
SciPy is not supported. It requires a number of system dependencies that are not available on Heroku.

You can, however, use this experimental anaconda buildpack:

https://github.com/kennethreitz/conda-buildpack

**Comment by icoxfog417** [comment]
Thank you for telling me the anaconda buildpack. It is very useful to do it.

The cause of error was [version up of heroku cedar](https://devcenter.heroku.com/articles/cedar).
I changed the dependency and it works fine. Thank you.
