### ISSUE TITLE
Pip except when upgrading from v52 > v60

### ISSUE THREAD

**Issue by samuelcolvin** [heroku/heroku-buildpack-python#230]
We're using heroku-buildpack-multi and therefore specify the version of the python build pack we want in `.buildpacks`.

Until now we've been using v52 (it was the latest version) when we last worried about this, and we're now trying to upgrade to v60.

We get the following error when attempting to push with `v60`:
```
remote: Building source:        
remote: 
remote: -----> Deleting 1 files matching .slugignore patterns.        
remote: -----> Fetching custom git buildpack... done        
remote: -----> Multipack app detected        
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-python.git        
remote: =====> Detected Framework: Python        
remote: -----> Uninstalling stale dependencies        
remote: /app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.        
remote:   InsecurePlatformWarning        
remote: You are using pip version 7.0.1, however version 7.0.3 is available.        
remote: You should consider upgrading via the 'pip install --upgrade pip' command.        
remote: Exception:        
remote: Traceback (most recent call last):        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/basecommand.py", line 223, in main        
remote:     status = self.run(options, args)        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/commands/uninstall.py", line 69, in run        
remote:     wheel_cache=wheel_cache):        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/req/req_file.py", line 86, in parse_requirements        
remote:     for req in req_iter:        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/req/req_file.py", line 130, in process_line        
remote:     wheel_cache=wheel_cache        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/req/req_install.py", line 207, in from_line        
remote:     wheel_cache=wheel_cache)        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/req/req_install.py", line 66, in __init__        
remote:     req = pkg_resources.Requirement.parse(req)        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse        
remote:     reqs = list(parse_requirements(s))        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2904, in parse_requirements        
remote:     "version spec")        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2869, in scan_list        
remote:     raise ValueError(msg, line, "at", line[p:])        
remote: ValueError: ('Expected version spec in', 'There was a problem loading the given requirements files.', 'at', ' was a problem loading the given requirements files.')        
remote: 
remote: -----> Installing dependencies with pip        
remote: Exception:        
remote: Traceback (most recent call last):        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/basecommand.py", line 223, in main        
remote:     status = self.run(options, args)        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/commands/install.py", line 268, in run        
remote:     wheel_cache        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/basecommand.py", line 287, in populate_requirement_set        
remote:     wheel_cache=wheel_cache):        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/req/req_file.py", line 86, in parse_requirements        
remote:     for req in req_iter:        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/req/req_file.py", line 130, in process_line        
remote:     wheel_cache=wheel_cache        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/req/req_install.py", line 207, in from_line        
remote:     wheel_cache=wheel_cache)        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/req/req_install.py", line 66, in __init__        
remote:     req = pkg_resources.Requirement.parse(req)        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2960, in parse        
remote:     reqs = list(parse_requirements(s))        
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2891, in parse_requirements        
remote:     raise ValueError("Missing distribution spec", line)        
remote: ValueError: ('Missing distribution spec', '== 0.0.3')        
remote: 
remote: 
remote:  !     Push rejected, failed to compile Multipack app        
remote: 
remote: Verifying deploy...        
remote: 
remote: ! Push rejected to xxx.        
remote: 
```

`.buildpacks` is just:
```
https://github.com/heroku/heroku-buildpack-python.git#v60
```
(we've been meaning to have the node buildpack to allow js compression etc for ages but haven't got round to it)

what's going on, are we doing something dumb?

**Comment by samuelcolvin** [comment]
ok, definitely something weird going on with v60, I've just gone back to v59 and push/deploy went fine.

**Comment by samuelcolvin** [comment]
bump. Anyone? If Heroku's python build pack really does have a bug I'm kind of amazed no one has responded to this.

**Comment by cyx** [comment]
Hi,

I'm trying to reproduce this issue with the vanilla getting started app and couldn't. Would you be able to share your requirements.txt?

**Comment by samuelcolvin** [comment]
https://gist.github.com/samuelcolvin/24ed2c64af13eaa1497c
