### ISSUE TITLE
Issue with transitioning app from cedar-10 to cedar-14 / No module named urllib3

### ISSUE THREAD

**Issue by kvarga** [heroku/heroku-buildpack-python#294]
I've got an older app that I am updating and having to update to cedar-14 . Something is broken and I can't deploy it however.

It is a pretty standard Flask app:

```
$ tree -L 2
├── Procfile
├── README.md
├── env
│   ├── bin
│   ├── include
│   ├── lib
│   └── pip-selfcheck.json
├── links
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── server.py
│   ├── server.pyc
│   ├── static
│   └── templates
├── requirements.txt
└── runserver.py
```

requirements.txt
```Flask==0.10.1
gevent==1.1.1
greenlet==0.4.9
gunicorn==19.4.5
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
requests==2.9.1
urllib3==1.15.1
Werkzeug==0.11.5
```

However, when pushing I get the following error:
```
Counting objects: 196, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (172/172), done.
Writing objects: 100% (196/196), 100.20 KiB | 0 bytes/s, done.
Total 196 (delta 101), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote: ERROR:root:code for hash md5 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type md5
remote: ERROR:root:code for hash sha1 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha1
remote: ERROR:root:code for hash sha224 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha224
remote: ERROR:root:code for hash sha256 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha256
remote: ERROR:root:code for hash sha384 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha384
remote: ERROR:root:code for hash sha512 was not found.
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:     globals()[__func_name] = __get_hash(__func_name)
remote:   File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:     raise ValueError('unsupported hash type ' + name)
remote: ValueError: unsupported hash type sha512
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/bin/pip", line 9, in <module>
remote:     load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
remote:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 353, in load_entry_point
remote:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2302, in load_entry_point
remote:   File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2029, in load
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/__init__.py", line 10, in <module>
remote:     from pip.util import get_installed_distributions, get_prog
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/util.py", line 18, in <module>
remote:     from pip._vendor.distlib import version
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/_vendor/distlib/version.py", line 14, in <module>
remote:     from .compat import string_types
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip-1.5.4-py2.7.egg/pip/_vendor/distlib/compat.py", line 31, in <module>
remote:     from urllib2 import (Request, urlopen, URLError, HTTPError,
remote: ImportError: cannot import name HTTPSHandler
remote:      $ pip install -r requirements.txt
remote:        ERROR:root:code for hash md5 was not found.
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:            globals()[__func_name] = __get_hash(__func_name)
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:            raise ValueError('unsupported hash type ' + name)
remote:        ValueError: unsupported hash type md5
remote:        ERROR:root:code for hash sha1 was not found.
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:            globals()[__func_name] = __get_hash(__func_name)
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:            raise ValueError('unsupported hash type ' + name)
remote:        ValueError: unsupported hash type sha1
remote:        ERROR:root:code for hash sha224 was not found.
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:            globals()[__func_name] = __get_hash(__func_name)
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:            raise ValueError('unsupported hash type ' + name)
remote:        ValueError: unsupported hash type sha224
remote:        ERROR:root:code for hash sha256 was not found.
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:            globals()[__func_name] = __get_hash(__func_name)
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:            raise ValueError('unsupported hash type ' + name)
remote:        ValueError: unsupported hash type sha256
remote:        ERROR:root:code for hash sha384 was not found.
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:            globals()[__func_name] = __get_hash(__func_name)
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:            raise ValueError('unsupported hash type ' + name)
remote:        ValueError: unsupported hash type sha384
remote:        ERROR:root:code for hash sha512 was not found.
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 139, in <module>
remote:            globals()[__func_name] = __get_hash(__func_name)
remote:          File "/app/.heroku/python/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
remote:            raise ValueError('unsupported hash type ' + name)
remote:        ValueError: unsupported hash type sha512
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/bin/pip", line 9, in <module>
remote:            load_entry_point('pip==8.1.1', 'console_scripts', 'pip')()
remote:          File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 549, in load_entry_point
remote:          File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2543, in load_entry_point
remote:          File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2203, in load
remote:          File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2209, in resolve
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/__init__.py", line 16, in <module>
remote:            from pip.vcs import git, mercurial, subversion, bazaar  # noqa
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/vcs/mercurial.py", line 9, in <module>
remote:            from pip.download import path_to_url
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/download.py", line 39, in <module>
remote:            from pip._vendor import requests, six
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/requests/__init__.py", line 58, in <module>
remote:            from . import utils
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/requests/utils.py", line 26, in <module>
remote:            from .compat import parse_http_list as _parse_list_header
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/requests/compat.py", line 7, in <module>
remote:            from .packages import chardet
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
remote:            import urllib3
remote:        ImportError: No module named urllib3
remote: 
remote:  !     Push rejected, failed to compile Python app
remote: 
```

Any ideas? There are no config variables or buildpacks set

**Comment by kvarga** [comment]
Running `heroku repo:purge_cache -a project-name` resolved the issue.

**Comment by kennethreitz** [comment]
Was just about to suggest this :)

-------------

For the record, this *shouldn't* happen, but there is a very rare corner case where it does occur when migrating. I don't recall, off the top of my head, the underlying cause. But, glad you figured out the workaround. 

Sorry for the trouble!
