### ISSUE TITLE
'pip-diff: error: no such option: --hash' due to vendored pip 7.1.2

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-python#302]
We're currently using the Pip hash support added in pip 8.0.

However pip-pop run during the buildpack compile is made to use an older version of pip (7.1.2) as of:
https://github.com/heroku/heroku-buildpack-python/commit/0b7a1fc14e6e0a0e694f8e8da1a2e004ef2e53a7

This results in:
```
-----> Python app detected
Usage: pip-diff [options]
Traceback (most recent call last):
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 119, in <module>
    main()
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 114, in main
    diff(**kwargs)
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 85, in diff
    r1 = Requirements(r1)
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 28, in __init__
    self.load(reqfile)
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip-diff", line 39, in load
    for requirement in parse_requirements(reqfile, finder=finder, session=requests):
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 172, in process_line
    for req in parser:
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 119, in process_line
    opts, _ = parser.parse_args(shlex.split(options_str), defaults)
  File "/app/.heroku/python/lib/python2.7/optparse.py", line 1402, in parse_args
    self.error(str(err))
  File "/app/.heroku/python/lib/python2.7/optparse.py", line 1584, in error
    self.exit(2, "%s: error: %s\n" % (self.get_prog_name(), msg))
  File "/tmp/buildpack20160505-158-8vk2j6/vendor/pip-pop/pip/req/req_file.py", line 238, in parser_exit
    raise RequirementsFileParseError(msg)
pip.exceptions.RequirementsFileParseError: pip-diff: error: no such option: --hash
     $ pip install -r requirements.txt
```

The fix being to add support to pip-pop for pip 8.x (kennethreitz/pip-pop#10), to then update to that upstream version of pip-pop, and then to remove the outdated vendored version of pip from the buildpack.

**Comment by edmorley** [comment]
It's worth noting that the compile succeeds even with these errors, so it is only by inspection of the build logs that I happened to spot the exceptions.

Is it expected that the build continues regardless?

**Comment by edmorley** [comment]
@kennethreitz I don't suppose you know when you might be able to take a look at this? :-)
