### ISSUE TITLE
Cannot run installed python binary in subsequent buildpack

### ISSUE THREAD

**Issue by revmischa** [heroku/heroku-buildpack-python#325]
I want to run a python script when deploying my build, I'm not clear on how to do this. Is there a way to run a script when an app is deployed? Either by pushing and doing a release, or by promoting a build to production? 
I have a staging environment and a production environment, and I want to run database migrations on both environments. Currently I deploy to stage by pushing to a branch, and then if that's cool I promote it to master. The migration script needs to be run in both environments. I'm trying to do it with: https://github.com/revmischa/heroku-buildpack-alembic-migrate

**Comment by revmischa** [comment]
I am having trouble with executing a python script in a subsequent buildpack.

```
=== myapp-stage Buildpack URLs
1. heroku/python
2. https://github.com/revmischa/heroku-buildpack-nodejs-gulp.git
3. https://github.com/revmischa/heroku-buildpack-alembic-migrate.git
```

When it runs the final step, it gets an error saying it cannot import modules that were previously installed with pip in buildpack step 1.

```
-----> Running Alembic migration
+ /tmp/build_175e64ac842e30d225b8c12c6858c869/myapp-myapp-437327e430e2e06629779302239ffcebe2641513/.heroku/python/bin/python /tmp/build_175e64ac842e30d225b8c12c6858c869/myapp-myapp-437327e430e2e06629779302239ffcebe2641513/migrate.py db upgrade head
Traceback (most recent call last):
  File "/tmp/build_175e64ac842e30d225b8c12c6858c869/myapp-myapp-437327e430e2e06629779302239ffcebe2641513/migrate.py", line 8, in <module>
    from myapp.app import setup_app
  File "/tmp/build_175e64ac842e30d225b8c12c6858c869/myapp-myapp-437327e430e2e06629779302239ffcebe2641513/myapp/app.py", line 21, in <module>
    from flask_session import Session
ImportError: No module named flask_session
 !     Push rejected, failed to compile Alembic app.
```

**Comment by revmischa** [comment]
flask_session was definitely installed earlier:
```
       Successfully installed Flask-SQLAlchemy Flask-Session
```
