### ISSUE TITLE
Install with `-e .` causes "AssertionError: Egg-link /app does not match installed location"

### ISSUE THREAD

**Issue by NovaDev94** [heroku/heroku-buildpack-python#352]
Full trace

```
remote:        Exception:
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
remote:            status = self.run(options, args)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
remote:            prefix=options.prefix_path,
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
remote:            requirement.uninstall(auto_confirm=True)
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 703, in uninstall
remote:            '(at %s)' % (link_pointer, self.name, dist.location)
remote:        AssertionError: Egg-link /app does not match installed location of thumbor-exts (at /tmp/build_23ef6c062baa8332793413f38b4f8f4f)
```

My `requirements.txt`

```
-e .
```

My buildpacks (latest commit in `master`)

```
https://github.com/heroku/heroku-buildpack-python#573ded6d410d29dbec46da99e4b67122eb9a1ad7
```

**Comment by kennethreitz** [comment]
This should now longer be an issue, but you may need to purge your build cache:

```
$ heroku plugins:install heroku-repo
$ heroku repo:purge_cache
$ git push heroku master

**Comment by NovaDev94** [comment]
@kennethreitz The problem is gone after I run the `purge_cache`, however it raises the same error next time I make a deployment to Heroku.

**Comment by johbo** [comment]
I am seeing a similar issue, also having `-e .` in my requirements file.

Here is a traceback:

```
remote: -----> Python app detected
remote:      $ pip install -r requirements.txt
remote:        Collecting https://github.com/johbo/johbo-pytest-sqlalchemy/archive/v0.0.2.tar.gz#md5=8841b2b9f46994a26b6fdb3504f8272a (from -r /tmp/build_c1647d65e0c13911e768361310ed22d9/requirements-common.txt (line 32))
remote:          Downloading https://github.com/johbo/johbo-pytest-sqlalchemy/archive/v0.0.2.tar.gz
remote:        Obtaining file:///tmp/build_c1647d65e0c13911e768361310ed22d9 (from -r /tmp/build_c1647d65e0c13911e768361310ed22d9/requirements.txt (line 5))
remote:        Installing collected packages: lc-web
remote:          Found existing installation: lc-web 0.1.0
remote:        Exception:
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/pip-9.0.1-py3.5.egg/pip/basecommand.py", line 215, in main
remote:            status = self.run(options, args)
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/pip-9.0.1-py3.5.egg/pip/commands/install.py", line 342, in run
remote:            prefix=options.prefix_path,
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/pip-9.0.1-py3.5.egg/pip/req/req_set.py", line 778, in install
remote:            requirement.uninstall(auto_confirm=True)
remote:          File "/app/.heroku/python/lib/python3.5/site-packages/pip-9.0.1-py3.5.egg/pip/req/req_install.py", line 703, in uninstall
remote:            '(at %s)' % (link_pointer, self.name, dist.location)
remote:        AssertionError: Egg-link /tmp/build_ccc3636f4a321173a46527f869e812a0 does not match installed location of lc-web (at /tmp/build_c1647d65e0c13911e768361310ed22d9)
remote:  !     Push rejected, failed to compile Python app.
```

I have tried older versions of this buildpack, v85 seems to work fine as a workaround.

**Comment by kennethreitz** [comment]
this is now fixed!

**Comment by johbo** [comment]
Cool, thanks! I'll test it out as soon as possible.

**Comment by johbo** [comment]
Works with the current change. 👍
