### ISSUE TITLE
setuptools / six build failure

### ISSUE THREAD

**Issue by rhysyngsun** [heroku/heroku-buildpack-python#364]
We're observing that our builds that have started using the newer version of `setuptools` introduced in 893bdec. This appears related to benjaminp/six#183.

I'm also curious why we're seeing this our builds when the relevant change isn't in a tagged/released version?

Here's the relevant portion of the build output we're getting:

```
-----> Python app detected
-----> Running pre-compile hook
-----> Writing out SOURCE_VERSION to static/hash (REDACTED)
-----> Installing python-3.5.2
-----> Installing Setuptools (34.3.1)
Archive:  /app/tmp/buildpacks/e9f275a1b9ba0766057ba4819a5cc3ed5816eb96ae41f034c9495448822e0037099f955cfd488aad9a4ebdd138e19250a259b93ba461db6b897f6881a7d82b7c/vendor/setuptools-34.3.1.zip
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/CHANGES.rst  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/LICENSE  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/MANIFEST.in  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/README.rst  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/bootstrap.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/conftest.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/easy_install.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/launcher.c  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/msvc-build-launcher.cmd  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/pytest.ini  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setup.cfg  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setup.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/tox.ini  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/PKG-INFO  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/Makefile  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/conf.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/developer-guide.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/development.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/easy_install.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/formats.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/history.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/index.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/pkg_resources.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/python3.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/releases.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/requirements.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/roadmap.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/setuptools.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/_templates/indexsidebar.html  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/_theme/nature/theme.conf  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/_theme/nature/static/nature.css_t  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/docs/_theme/nature/static/pygments.css  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/pkg_resources/__init__.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/pkg_resources/api_tests.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/pkg_resources/tests/__init__.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/pkg_resources/tests/test_markers.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/pkg_resources/tests/test_pkg_resources.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/pkg_resources/tests/test_resources.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/__init__.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/archive_util.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/cli-32.exe  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/cli-64.exe  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/cli.exe  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/config.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/dep_util.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/depends.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/dist.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/extension.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/glob.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/gui-32.exe  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/gui-64.exe  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/gui.exe  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/launch.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/lib2to3_ex.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/monkey.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/msvc.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/namespaces.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/package_index.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/py26compat.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/py27compat.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/py31compat.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/py33compat.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/py36compat.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/sandbox.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/script (dev).tmpl  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/script.tmpl  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/site-patch.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/ssl_support.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/unicode_utils.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/version.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/windows_support.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/__init__.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/alias.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/bdist_egg.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/bdist_rpm.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/bdist_wininst.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/build_clib.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/build_ext.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/build_py.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/develop.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/easy_install.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/egg_info.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/install.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/install_egg_info.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/install_lib.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/install_scripts.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/launcher manifest.xml  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/py36compat.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/register.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/rotate.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/saveopts.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/sdist.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/setopt.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/test.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/upload.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/command/upload_docs.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/__init__.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/contexts.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/environment.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/files.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/fixtures.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/mod_with_constant.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/namespaces.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/py26compat.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/script-with-bom.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/server.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_archive_util.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_bdist_egg.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_build_clib.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_build_ext.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_build_py.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_config.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_dep_util.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_depends.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_develop.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_dist_info.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_easy_install.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_egg_info.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_find_packages.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_install_scripts.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_integration.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_manifest.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_msvc.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_namespaces.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_packageindex.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_sandbox.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_sdist.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_setuptools.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_test.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_unicode_utils.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_upload_docs.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/test_windows_wrappers.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/textwrap.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/indexes/test_links_priority/external.html  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/tests/indexes/test_links_priority/simple/foobar/index.html  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools.egg-info/PKG-INFO  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools.egg-info/SOURCES.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools.egg-info/dependency_links.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools.egg-info/entry_points.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools.egg-info/requires.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools.egg-info/top_level.txt  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools.egg-info/zip-safe  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/tests/manual_test.py  
  inflating: /tmp/tmp.Eh04VUevM4/setuptools-34.3.1/tests/test_pypi.py  
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/tmp/tmp.Eh04VUevM4/setuptools-34.3.1/setuptools/__init__.py", line 10, in <module>
    from six.moves import filter, map
ImportError: No module named 'six'
-----> Installing Pip (9.0.1)
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
     $ pip install -r requirements.txt
       /app/tmp/buildpacks/e9f275a1b9ba0766057ba4819a5cc3ed5816eb96ae41f034c9495448822e0037099f955cfd488aad9a4ebdd138e19250a259b93ba461db6b897f6881a7d82b7c/bin/steps/pip-install: line 20: /app/.heroku/python/bin/pip: No such file or directory
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by cclauss** [comment]
related to https://github.com/heroku/heroku-buildpack-python/commit/e26a0f04d93ff1491ec10076c8268879d2d479fc ?

**Comment by rhysyngsun** [comment]
@cclauss yup, we also already decided to just pin to v99.

**Comment by kennethreitz** [comment]
this should now be working
