### ISSUE TITLE
Failure to build Python app because of pip

### ISSUE THREAD

**Issue by vinitkumar** [heroku/heroku-buildpack-python#681]
```sh
remote: Traceback (most recent call last):
remote:   File "/app/tmp/buildpacks/779a8bbfbbe7e1b715476c0b23fc63a2103b3e4131eda558669aba8fb5e6e05682419376144189b29beb5dee6d7626b4d3385edb0954bffea6c67d8cf622fd51/vendor/pip-pop/pip-diff", line 15, in <module>
remote:     from pip.req import parse_requirements
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>
remote:     from .req_install import InstallRequirement
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/req/req_install.py", line 25, in <module>
remote:     import pip.wheel
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/wheel.py", line 28, in <module>
remote:     from pip.download import path_to_url, unpack_url
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/download.py", line 40, in <module>
remote:     from pip._vendor import requests, six
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 83, in <module>
remote:     from pip._internal.compat import WINDOWS
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/__init__.py", line 42, in <module>
remote:     from pip._internal import cmdoptions
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
remote:     from pip._internal.index import (
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/index.py", line 15, in <module>
remote:     from pip._vendor import html5lib, requests, six
remote: ImportError: cannot import name requests
remote: mount: can't find failure.bad-requirements in /etc/fstab or /etc/mtab
remote: -----> Installing requirements with pip
remote:        Traceback (most recent call last):
remote:          File "/app/.heroku/python/bin/pip", line 7, in <module>
remote:            from pip._internal import main
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/__init__.py", line 42, in <module>
remote:            from pip._internal import cmdoptions
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
remote:            from pip._internal.index import (
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip/_internal/index.py", line 15, in <module>
remote:            from pip._vendor import html5lib, requests, six
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 86, in <module>
remote:            from pip._vendor.urllib3.contrib import pyopenssl
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
remote:            import OpenSSL.SSL
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
remote:            from OpenSSL import rand, crypto, SSL
remote:          File "/app/.heroku/python/lib/python2.7/site-packages/OpenSSL/SSL.py", line 118, in <module>
remote:            SSL_ST_INIT = _lib.SSL_ST_INIT
remote:        AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
```

We are not able to release our latest code to heroku due to this. Could you please look into it?

**Comment by cclauss** [comment]
Related to #680 ?

**Comment by kennethreitz** [comment]
This should now be resolved.

**Comment by vinitkumar** [comment]
@kennethreitz Indeed. We were able to deploy to our app today. Thanks for the effort.
