### ISSUE TITLE
Latest Python version but Heroku still thinks I have an unsupported older one

### ISSUE THREAD

**Issue by antoinecomp** [heroku/heroku-buildpack-python#717]
Hi there, I try to deploy [my Flask app](https://github.com/antoinecomp/moodbot) on Heroku which works with Python 3.5.2 and Python 3.6.5. I know Python 3.5.2 is outdated but each time I push it tells me I'm using an outdated version of the app depite of the Pipfile

Here is the log:
```
mike@mike-thinks:~/Programing/Rasa/myflaskapp$ git push heroku master
Counting objects: 31715, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (23971/23971), done.
Writing objects: 100% (31715/31715), 293.38 MiB | 1.10 MiB/s, done.
Total 31715 (delta 7105), reused 31669 (delta 7076)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote:  !     The latest version of Python 3 is python-3.6.5 (you are using python-3.5.2, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-3.6.5).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Installing python-3.5.2
remote: -----> Installing pip
remote: Traceback (most recent call last):
remote:   File "/app/tmp/buildpacks/779a8bbfbbe7e1b715476c0b23fc63a2103b3e4131eda558669aba8fb5e6e05682419376144189b29beb5dee6d7626b4d3385edb0954bffea6c67d8cf622fd51/vendor/pipenv-to-pip", line 23, in <module>
remote:     main()
remote:   File "/app/tmp/buildpacks/779a8bbfbbe7e1b715476c0b23fc63a2103b3e4131eda558669aba8fb5e6e05682419376144189b29beb5dee6d7626b4d3385edb0954bffea6c67d8cf622fd51/vendor/pipenv-to-pip", line 11, in main
remote:     lockfile = json.load(f)
remote:   File "/app/.heroku/python/lib/python3.5/json/__init__.py", line 268, in load
remote:     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
remote:   File "/app/.heroku/python/lib/python3.5/json/__init__.py", line 312, in loads
remote:     s.__class__.__name__))
remote: TypeError: the JSON object must be str, not 'bytes'
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to rosenberg-moodbot.
remote: 
To https://git.heroku.com/rosenberg-moodbot.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/rosenberg-moodbot.git'
```

And here is the Pipfile:

```
[[source]]
url = "https://pypi.python.org/simple"

[packages]
requests = { extras = ['socks'] }

[requires]
python_full_version = "3.6.5"
```

The question was asked [on stackoverflow](https://stackoverflow.com/questions/50284847/heroku-push-error-python-3-6) but got no useful answers.

**Comment by KevinBrolly** [comment]
Hi @antoinecomp,

This is because you already have a `runtime.txt` file in your repo with `python-3.5.2` - https://github.com/antoinecomp/moodbot/blob/master/runtime.txt

The pipenv python version detection will only work if you do not already have a `runtime.txt` file in your root directory - https://github.com/heroku/heroku-buildpack-python/blob/master/bin/steps/pipenv-python-version#L7

So if you want detection off your pipfile to work you have to remove the `runtime.txt` file, alternatively you could just update the `runtime.txt` file to the version you want.
