### ISSUE TITLE
Module not found by Heroku despite being in the requirements

### ISSUE THREAD

**Issue by antoinecomp** [heroku/heroku-buildpack-python#719]
I deployed a [Python Flask app][1] on Heroku but it failed to build because not finding the specified module : `flask` which was in the requirements though. The error is :

    ModuleNotFoundError: No module named 'flask'

I checked [Raja Simon's answer][2] and used the `$pip freeze > requirements.txt` command. It gave logs quite longer but with the similar error at the end. 

Here are the logs :

    (MyFlaskAppEnv) mike@mike-thinks:~/Programing/Rasa/myflaskapp$ heroku run pip freeze
    2018-06-27T11:42:34.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
    2018-06-27T11:43:13.411707+00:00 heroku[web.1]: Starting process with command `python app.py 21178`
    2018-06-27T11:43:15.837860+00:00 heroku[web.1]: Process exited with status 1
    2018-06-27T11:43:15.856692+00:00 heroku[web.1]: State changed from starting to crashed
    2018-06-27T11:43:15.772353+00:00 app[web.1]: Traceback (most recent call last):
    2018-06-27T11:43:15.772387+00:00 app[web.1]: File "app.py", line 1, in <module>
    2018-06-27T11:43:15.772516+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
    2018-06-27T11:43:15.772564+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
    2018-06-27T11:43:15.858551+00:00 heroku[web.1]: State changed from crashed to starting
    2018-06-27T11:43:09.193489+00:00 app[api]: Deploy 25f77237 by user antoine.compagnie@gmail.com
    2018-06-27T11:43:09.193489+00:00 app[api]: Release v4 created by user antoine.compagnie@gmail.com
    2018-06-27T11:43:09.000000+00:00 app[api]: Build succeeded
    2018-06-27T11:43:09.215426+00:00 app[api]: Scaled to web@1:Free by user antoine.compagnie@gmail.com
    2018-06-27T11:43:21.161561+00:00 heroku[web.1]: Starting process with command `python app.py 59367`
    2018-06-27T11:43:23.924087+00:00 heroku[web.1]: Process exited with status 1
    2018-06-27T11:43:23.940890+00:00 heroku[web.1]: State changed from starting to crashed
    2018-06-27T11:43:23.841663+00:00 app[web.1]: Traceback (most recent call last):
    2018-06-27T11:43:23.841688+00:00 app[web.1]: File "app.py", line 1, in <module>
    2018-06-27T11:43:23.841917+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
    2018-06-27T11:43:23.841923+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
    2018-06-27T11:54:43.888837+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=rosenberg-moodbot.herokuapp.com request_id=e4428bfb-012c-43dc-a7b4-a67e257a7853 fwd="82.1.184.42" dyno= connect= service= status=503 bytes= protocol=https
    2018-06-27T11:54:44.411389+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=rosenberg-moodbot.herokuapp.com request_id=936933c2-d48d-4106-8607-f5e2a45f430a fwd="82.1.184.42" dyno= connect= service= status=503 bytes= protocol=https
    2018-06-27T11:54:44.411939+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=rosenberg-moodbot.herokuapp.com request_id=7f49a28a-778b-47aa-9205-92d56a56c73c fwd="82.1.184.42" dyno= connect= service= status=503 bytes= protocol=https
    2018-06-27T11:55:07.458967+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=rosenberg-moodbot.herokuapp.com request_id=f2d7e020-b654-42da-83f3-631c8a116442 fwd="82.1.184.42" dyno= connect= service= status=503 bytes= protocol=https
    2018-06-27T12:03:38.241868+00:00 heroku[web.1]: State changed from crashed to starting
    2018-06-27T12:03:42.317464+00:00 heroku[web.1]: Starting process with command `python app.py 28610`
    2018-06-27T12:03:44.695629+00:00 heroku[web.1]: Process exited with status 1
    2018-06-27T12:03:44.625237+00:00 app[web.1]: Traceback (most recent call last):
    2018-06-27T12:03:44.625272+00:00 app[web.1]: File "app.py", line 1, in <module>
    2018-06-27T12:03:44.625441+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
    2018-06-27T12:03:44.625492+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
    2018-06-27T12:03:44.791879+00:00 heroku[web.1]: State changed from starting to crashed
    2018-06-27T12:09:07.960949+00:00 app[api]: Starting process with command `pip freeze` by user antoine.compagnie@gmail.com
    2018-06-27T12:09:14.153229+00:00 heroku[run.8725]: State changed from up to complete
    2018-06-27T12:09:14.083206+00:00 heroku[run.8725]: Awaiting client
    2018-06-27T12:09:14.134697+00:00 heroku[run.8725]: State changed from starting to up
    2018-06-27T12:09:14.121827+00:00 heroku[run.8725]: Error R13 (Attach error) -> Failed to attach to process
    2018-06-27T12:09:14.127236+00:00 heroku[run.8725]: Process exited with status 128
    2018-06-27T12:09:18.023627+00:00 app[api]: Starting process with command `pip freeze` by user antoine.compagnie@gmail.com
    2018-06-27T12:09:22.543943+00:00 heroku[run.7995]: Awaiting client
    2018-06-27T12:09:22.572262+00:00 heroku[run.7995]: Starting process with command `pip freeze`
    2018-06-27T12:09:22.714123+00:00 heroku[run.7995]: State changed from starting to up
    2018-06-27T12:09:27.866504+00:00 heroku[run.7995]: Process exited with status 0
    2018-06-27T12:09:27.884656+00:00 heroku[run.7995]: State changed from up to complete
    2018-06-27T12:10:47.411648+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=rosenberg-moodbot.herokuapp.com request_id=865fbea1-bf7b-43a7-82e1-aaa3be505e7b fwd="82.1.184.42" dyno= connect= service= status=503 bytes= protocol=https
    2018-06-27T12:11:43.794922+00:00 heroku[run.1331]: Awaiting client
    2018-06-27T12:11:43.833108+00:00 heroku[run.1331]: Starting process with command `pip freeze`
    2018-06-27T12:11:43.925237+00:00 heroku[run.1331]: State changed from starting to up
    2018-06-27T12:11:39.579643+00:00 app[api]: Starting process with command `pip freeze` by user antoine.compagnie@gmail.com
    2018-06-27T12:11:48.939978+00:00 heroku[run.1331]: Process exited with status 0
    2018-06-27T12:11:48.960226+00:00 heroku[run.1331]: State changed from up to complete
    2018-06-27T12:12:30.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
    2018-06-27T12:12:49.441456+00:00 app[api]: Deploy 55bbe098 by user antoine.compagnie@gmail.com
    2018-06-27T12:12:49.441456+00:00 app[api]: Release v5 created by user antoine.compagnie@gmail.com
    2018-06-27T12:12:49.910214+00:00 heroku[web.1]: State changed from crashed to starting
    2018-06-27T12:12:49.000000+00:00 app[api]: Build succeeded
    2018-06-27T12:12:53.359381+00:00 heroku[web.1]: Starting process with command `python app.py 21411`
    2018-06-27T12:12:54.939693+00:00 heroku[web.1]: Process exited with status 1
    2018-06-27T12:12:54.900467+00:00 app[web.1]: Traceback (most recent call last):
    2018-06-27T12:12:54.900502+00:00 app[web.1]: File "app.py", line 1, in <module>
    2018-06-27T12:12:54.900600+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
    2018-06-27T12:12:54.900606+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
    2018-06-27T12:12:54.954666+00:00 heroku[web.1]: State changed from starting to crashed
    2018-06-27T12:13:01.350585+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=rosenberg-moodbot.herokuapp.com request_id=8a3ae221-135d-4704-bfb3-92cf9339d766 fwd="82.1.184.42" dyno= connect= service= status=503 bytes= protocol=https

And here are my [requirements.txt][3] which includes `flask==1.0.2`

And here is the output of `$heroku run pip freeze` which shows `flask` doesn't seem to be part of it.

    (MyFlaskAppEnv) mike@mike-thinks:~/Programing/Rasa/myflaskapp$ heroku run pip freeze
    Running pip freeze on ⬢ rosenberg-moodbot... up, run.9642 (Free)
    certifi==2018.4.16
    chardet==3.0.4
    idna==2.7
    pipenv==11.8.2
    PySocks==1.6.8
    requests==2.19.1
    urllib3==1.23
    virtualenv==16.0.0
    virtualenv-clone==0.3.0
    You are using pip version 9.0.2, however version 10.0.1 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

  [1]: https://github.com/antoinecomp/moodbot
  [2]: https://stackoverflow.com/questions/27911978/heroku-no-module-named-flask-though-it-is-in-requirements-txt/27919296
  [3]: https://github.com/antoinecomp/moodbot/blob/master/requirements.txt

**Comment by edmorley** [comment]
Hi! There is a `Pipfile` and `Pipfile.lock` in that repository:
https://github.com/antoinecomp/moodbot/blob/55bbe09827810114c5369c1956293dd270b82957/Pipfile
https://github.com/antoinecomp/moodbot/blob/55bbe09827810114c5369c1956293dd270b82957/Pipfile.lock

...which this buildpack prioritises over pip installing `requirements.txt`:
https://github.com/heroku/heroku-buildpack-python/blob/d18f1fedd87c209d47969e5f22bf1d6767fcbb00/bin/steps/pipenv#L54

I would either remove both of those files (if you're not wanting to use Pipenv) or else make sure all dependencies are listed in `Pipfile`.

**Comment by sigmavirus24** [comment]
@edmorley seems to have nailed this right on the head. I'm going to close this since the answer is in their comment and this is not a problem with the buildpack.

Cheers!

**Comment by antoinecomp** [comment]
@edmorley 
Thank you for your answer! Yet, if I remove Pipfile, I come back to the ["Latest Python version but Heroku still thinks I have an unsupported older one"](https://github.com/heroku/heroku-buildpack-python/issues/717#issuecomment-400606733) issue. So how can I list all dependencies in Pipfile as far as I have a number in the [requirements.txt](https://github.com/antoinecomp/moodbot/blob/master/requirements.txt) or remove them and being able not having the former issue.

**Comment by antoinecomp** [comment]
@edmorley 
Many thanks, it seems that the app is deployed then. Yet it wasn't able to build because of the first error I mentioned in this post: `No module named 'flask'`. Is it because there is Flask in the [requirements.txt](https://github.com/antoinecomp/moodbot/blob/master/requirements.txt) rather than flask ?

Here are the logs,

```bash
2018-06-28T11:16:22.872822+00:00 heroku[web.1]: Process exited with status 1
2018-06-28T11:16:22.890781+00:00 heroku[web.1]: State changed from starting to crashed
2018-06-28T11:16:22.814225+00:00 app[web.1]: Traceback (most recent call last):
2018-06-28T11:16:22.814303+00:00 app[web.1]: File "app.py", line 1, in <module>
2018-06-28T11:16:22.814508+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
2018-06-28T11:16:22.814552+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
2018-06-28T16:52:43.240293+00:00 heroku[web.1]: State changed from crashed to starting
2018-06-28T16:52:46.676238+00:00 heroku[web.1]: Starting process with command `python app.py 28342`
2018-06-28T16:52:48.428729+00:00 heroku[web.1]: Process exited with status 1
2018-06-28T16:52:48.372334+00:00 app[web.1]: Traceback (most recent call last):
2018-06-28T16:52:48.372354+00:00 app[web.1]: File "app.py", line 1, in <module>
2018-06-28T16:52:48.372476+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
2018-06-28T16:52:48.372492+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
2018-06-28T16:52:48.450286+00:00 heroku[web.1]: State changed from starting to crashed
2018-06-28T21:23:47.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
2018-06-28T21:23:55.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-28T21:29:56.485810+00:00 app[api]: Starting process with command `echo /home/mike/bin:/home/mike/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-version/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin:/usr/local/hadoop/bin` by user antoine.compagnie@gmail.com
2018-06-28T21:30:00.869693+00:00 heroku[run.2949]: Awaiting client
2018-06-28T21:30:01.075084+00:00 heroku[run.2949]: State changed from starting to up
2018-06-28T21:30:00.940408+00:00 heroku[run.2949]: Starting process with command `echo /home/mike/bin:/home/mike/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-version/bin:/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin:/usr/local/hadoop/bin`
2018-06-28T21:30:05.568776+00:00 heroku[run.2949]: Process exited with status 0
2018-06-28T21:30:05.710514+00:00 heroku[run.2949]: State changed from up to complete
2018-06-28T22:44:55.861152+00:00 heroku[web.1]: State changed from crashed to starting
2018-06-28T22:44:59.382926+00:00 heroku[web.1]: Starting process with command `python app.py 23829`
2018-06-28T22:45:01.225321+00:00 heroku[web.1]: Process exited with status 1
2018-06-28T22:45:01.167528+00:00 app[web.1]: File "app.py", line 1, in <module>
2018-06-28T22:45:01.167431+00:00 app[web.1]: Traceback (most recent call last):
2018-06-28T22:45:01.167538+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
2018-06-28T22:45:01.167574+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
2018-06-28T22:45:01.245832+00:00 heroku[web.1]: State changed from starting to crashed
2018-06-29T04:21:23.689944+00:00 heroku[web.1]: State changed from crashed to starting
2018-06-29T04:21:28.080450+00:00 heroku[web.1]: Starting process with command `python app.py 25486`
2018-06-29T04:21:30.400848+00:00 heroku[web.1]: Process exited with status 1
2018-06-29T04:21:30.419854+00:00 heroku[web.1]: State changed from starting to crashed
2018-06-29T04:21:30.358814+00:00 app[web.1]: Traceback (most recent call last):
2018-06-29T04:21:30.358839+00:00 app[web.1]: File "app.py", line 1, in <module>
2018-06-29T04:21:30.358919+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
2018-06-29T04:21:30.358922+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
2018-06-29T09:57:42.990601+00:00 heroku[web.1]: State changed from crashed to starting
2018-06-29T09:57:48.641471+00:00 heroku[web.1]: Starting process with command `python app.py 10453`
2018-06-29T09:57:51.375542+00:00 heroku[web.1]: State changed from starting to crashed
2018-06-29T09:57:51.355764+00:00 heroku[web.1]: Process exited with status 1
2018-06-29T09:57:51.286505+00:00 app[web.1]: Traceback (most recent call last):
2018-06-29T09:57:51.286531+00:00 app[web.1]: File "app.py", line 1, in <module>
2018-06-29T09:57:51.286695+00:00 app[web.1]: from flask import Flask, render_template, flash, redirect, url_for, session, request, logging, jsonify
2018-06-29T09:57:51.290278+00:00 app[web.1]: ModuleNotFoundError: No module named 'flask'
2018-06-29T10:04:16.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
2018-06-29T10:04:24.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T10:04:24.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T10:09:16.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
2018-06-29T10:09:25.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T10:09:25.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:39:05.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
2018-06-29T14:39:26.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:39:26.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:41:40.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
2018-06-29T14:41:58.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:41:58.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:44:47.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
2018-06-29T14:45:18.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:45:18.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:47:16.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
2018-06-29T14:48:13.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:48:13.000000+00:00 app[api]: Build failed -- check your build logs
2018-06-29T14:50:35.000000+00:00 app[api]: Build started by user antoine.compagnie@gmail.com
2018-06-29T14:57:50.143807+00:00 app[api]: Release v6 created by user antoine.compagnie@gmail.com
2018-06-29T14:57:50.143807+00:00 app[api]: Deploy a46a83c1 by user antoine.compagnie@gmail.com
2018-06-29T14:57:50.368801+00:00 heroku[web.1]: State changed from crashed to starting
2018-06-29T14:58:09.477528+00:00 heroku[web.1]: Starting process with command `python app.py 8495`
2018-06-29T14:58:11.763411+00:00 app[web.1]: * Serving Flask app "app" (lazy loading)
2018-06-29T14:58:11.763460+00:00 app[web.1]: * Environment: production
2018-06-29T14:58:11.763462+00:00 app[web.1]: WARNING: Do not use the development server in a production environment.
2018-06-29T14:58:11.763463+00:00 app[web.1]: Use a production WSGI server instead.
2018-06-29T14:58:11.763468+00:00 app[web.1]: * Debug mode: on
2018-06-29T14:58:11.779488+00:00 app[web.1]: * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
2018-06-29T14:58:11.780191+00:00 app[web.1]: * Restarting with stat
2018-06-29T14:58:12.208077+00:00 app[web.1]: * Debugger is active!
2018-06-29T14:58:12.209463+00:00 app[web.1]: * Debugger PIN: 273-406-467
2018-06-29T14:58:48.000000+00:00 app[api]: Build succeeded
2018-06-29T14:59:09.864388+00:00 heroku[web.1]: State changed from starting to crashed
2018-06-29T14:59:09.867654+00:00 heroku[web.1]: State changed from crashed to starting
2018-06-29T14:59:09.778434+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-06-29T14:59:09.778525+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-06-29T14:59:09.843654+00:00 heroku[web.1]: Process exited with status 137
2018-06-29T14:59:28.771310+00:00 heroku[web.1]: Starting process with command `python app.py 47616`
2018-06-29T14:59:30.750806+00:00 app[web.1]: * Serving Flask app "app" (lazy loading)
2018-06-29T14:59:30.750839+00:00 app[web.1]: * Environment: production
2018-06-29T14:59:30.750905+00:00 app[web.1]: WARNING: Do not use the development server in a production environment.
2018-06-29T14:59:30.750959+00:00 app[web.1]: Use a production WSGI server instead.
2018-06-29T14:59:30.751003+00:00 app[web.1]: * Debug mode: on
2018-06-29T14:59:30.767209+00:00 app[web.1]: * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
2018-06-29T14:59:30.767929+00:00 app[web.1]: * Restarting with stat
2018-06-29T14:59:31.144001+00:00 app[web.1]: * Debugger is active!
2018-06-29T14:59:31.145021+00:00 app[web.1]: * Debugger PIN: 146-893-492
2018-06-29T15:00:29.078005+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-06-29T15:00:29.078005+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-06-29T15:00:29.140040+00:00 heroku[web.1]: Process exited with status 137
2018-06-29T15:00:29.207951+00:00 heroku[web.1]: State changed from starting to crashed
2018-06-29T15:00:31.662320+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=rosenberg-moodbot.herokuapp.com request_id=57428692-f8fb-4dec-9db0-0815d88a8a5c fwd="193.60.231.83" dyno= connect= service= status=503 bytes= protocol=https
2018-06-29T15:00:32.186024+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=rosenberg-moodbot.herokuapp.com request_id=7b493757-3d0f-48a3-b4c3-cb170ecd1aac fwd="193.60.231.83" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by edmorley** [comment]
> Is it because there is Flask in the requirements.txt rather than flask ?

The capitalisation of the package on PyPI is `Flask` and the module to import is `flask`:
http://flask.pocoo.org/

...so what you have is correct.

Looking at the logs, it appears the latest build succeeded - so the error you quoted is actually from a previous build not the latest.

The actual latest error is:
```
2018-06-29T15:00:29.078005+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
```

And it's because the app isn't listening to the correct port:
```
2018-06-29T14:58:11.779488+00:00 app[web.1]: * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
```

It needs to be listening on the port specified by the environment variable `PORT` instead. See:
https://devcenter.heroku.com/articles/dynos#networking
https://devcenter.heroku.com/articles/dynos#web-dynos

Also from the logs it looks like the app is being run in debug mode, which is insecure:
```
2018-06-29T14:59:30.750905+00:00 app[web.1]: WARNING: Do not use the development server in a production environment.
2018-06-29T14:59:30.750959+00:00 app[web.1]: Use a production WSGI server instead.
```

I would check out:
http://flask.pocoo.org/docs/1.0/tutorial/deploy/#run-with-a-production-server
https://devcenter.heroku.com/articles/python-gunicorn
