### ISSUE TITLE
heroku do not install requirements.txt 

### ISSUE THREAD

**Issue by Nogrode** [heroku/heroku-buildpack-python#986]
Hi,
we are currently working on a Django app, now we wanted to deploy it with Heroku. For this, we followed these [these](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Deployment) guide.

The command `git push Heroku master` failed. It fails because it executes the command `python orchestra_Code/manage.py collectstatic --noinput`, in which "import dj_database_url" is executed, which fails. 
Since this module does not exist. But if the requirements file would be installed first, the module would exist.

I think the problem is that he is trying to install the dependencies through Pipenv. I don't know why he's doing it or how to change it. Can anyone here help me?

the requirements.txt file is also in the root folder.

The project can be found [here](https://gitlab.com/lilolunatic/orchestra-code/-/tree/deploy)
(on the deploy branch)

```
~/orchestra-code$ cat requirements.txt 
# --snip--
dj-database-url==0.5.0
Django==2.2.7
django-cors-headers==3.2.0
# --snip--
```

root directory:
```
~/orchestra-code$ ls
accounts     manage.py         orchestra          README.md         sheet
frontend     media             package.json       requirements.txt  webpack.config.js
group        modules           package-lock.json  runtime.txt       yarn.lock
instruments  myapp_models.png  Procfile           score
```

Error message:
```
~/orchestra-code$ git push heroku master
Counting objects: 31030, done.
Compressing objects: 100% (18937/18937), done.
Writing objects: 100% (31030/31030), 27.90 MiB | 22.69 MiB/s, done.
Total 31030 (delta 10918), reused 30969 (delta 10879)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
remote:                         Detected buildpacks: Python,Node.js
remote:                         See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
remote: -----> Python app detected
remote: cp: cannot stat '/tmp/build_e7181e2a2905ca59023a2c4e7bc82dc4/requirements.txt': No such file or directory
remote: -----> Installing python-3.7.7
remote: -----> Installing pip
remote: -----> Installing dependencies with Pipenv 2018.5.18…
remote:        Installing dependencies from Pipfile.lock (5b4024)…
remote: -----> Installing SQLite3
remote: -----> $ python orchestra_Code/manage.py collectstatic --noinput
remote:        Traceback (most recent call last):
remote:          File "orchestra_Code/manage.py", line 21, in <module>
remote:            main()
remote:          File "orchestra_Code/manage.py", line 17, in main
remote:            execute_from_command_line(sys.argv)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
remote:            utility.execute()
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
remote:            django.setup()
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
remote:            apps.populate(settings.INSTALLED_APPS)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
remote:            app_config = AppConfig.create(entry)
remote:          File "/app/.heroku/python/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
remote:            module = import_module(entry)
remote:          File "/app/.heroku/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
remote:            return _bootstrap._gcd_import(name[level:], package, level)
remote:          File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
remote:          File "<frozen importlib._bootstrap>", line 983, in _find_and_load
remote:          File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
remote:        ModuleNotFoundError: No module named 'django_extensions'
remote: 
remote:  !     Error while running '$ python orchestra_Code/manage.py collectstatic --noinput'.
remote:        See traceback above for details.
remote: 
remote:        You may need to update application code to resolve this error.
remote:        Or, you can disable collectstatic for this application:
remote: 
remote:           $ heroku config:set DISABLE_COLLECTSTATIC=1
remote: 
remote:        https://devcenter.heroku.com/articles/django-assets
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
```

**Comment by Nogrode** [comment]
I found the problem myself, I thought I could push from another branch. Once I got it from the master, it worked.
